[mypy]
files = src, tests
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_incomplete_defs = False
disallow_untyped_defs = False
check_untyped_defs = False
no_implicit_optional = False
ignore_missing_imports = True
strict_optional = True

[mypy-binance.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-streamlit.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-plotly.*]
ignore_missing_imports = True
