name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us fix it quickly.

  - type: checkboxes
    id: before-reporting
    attributes:
      label: Before Reporting
      description: Have you checked these items?
      options:
        - label: I've searched for existing issues
          required: true
        - label: I'm using the latest version
          required: true
        - label: I've read the documentation
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug
      placeholder: |
        What happened?
        What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: dropdown
    id: environment-os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Docker
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Python version (output of `python --version`)
      placeholder: "3.12.0"
    validations:
      required: true

  - type: input
    id: docker-version
    attributes:
      label: Docker Version (if applicable)
      description: Output of `docker --version`
      placeholder: "Docker version 24.0.0"

  - type: textarea
    id: error-message
    attributes:
      label: Error Messages or Log Output
      description: Include full stack trace or error messages
      render: python

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Anything else that might help?
        - Configuration files
        - Screenshots
        - Links to related issues
      placeholder: Add any other context here...

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Would you be willing to help fix this bug?
      options:
        - label: I can submit a PR with a fix